Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 30

Metrics/PerceivedComplexity:
  Enabled: false
